
checker_actions:
    -
        name: 'sampleChecker | 样例'
        skip: False
        auto: False
        description: '这是一个简单的样例！'
        handler: sample_check
    -
        name: 'sample02Checker | 样例02'
        skip: False
        auto: False
        description: '这是一个简单的样例02！'
        handler: sample02_check
