# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core\resources\check_dialog.ui'
#
# Created: Tue Sep 19 11:26:47 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_check_dialog(object):
    def setupUi(self, check_dialog):
        check_dialog.setObjectName("check_dialog")
        check_dialog.resize(693, 504)
        check_dialog.setStyleSheet("")
        self.main_layout = QtGui.QVBoxLayout(check_dialog)
        self.main_layout.setSpacing(0)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_area_frame = QtGui.QFrame(check_dialog)
        self.left_area_frame.setMinimumSize(QtCore.QSize(300, 0))
        self.left_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.left_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.left_area_frame.setObjectName("left_area_frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.left_area_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_area_top_frame = QtGui.QFrame(self.left_area_frame)
        self.left_area_top_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.left_area_top_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.left_area_top_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.left_area_top_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.left_area_top_frame.setObjectName("left_area_top_frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.left_area_top_frame)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.left_area_top_frame)
        self.label.setStyleSheet("font: 87 9pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(93, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.auto_check = QtGui.QCheckBox(self.left_area_top_frame)
        self.auto_check.setChecked(True)
        self.auto_check.setObjectName("auto_check")
        self.horizontalLayout.addWidget(self.auto_check)
        self.check_seleted = QtGui.QCheckBox(self.left_area_top_frame)
        self.check_seleted.setObjectName("check_seleted")
        self.horizontalLayout.addWidget(self.check_seleted)
        self.refresh_btn = QtGui.QToolButton(self.left_area_top_frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon)
        self.refresh_btn.setAutoRaise(True)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.batch_run_btn = QtGui.QToolButton(self.left_area_top_frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/play_icon_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batch_run_btn.setIcon(icon1)
        self.batch_run_btn.setAutoRaise(True)
        self.batch_run_btn.setObjectName("batch_run_btn")
        self.horizontalLayout.addWidget(self.batch_run_btn)
        self.continue_btn = QtGui.QToolButton(self.left_area_top_frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/gono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.continue_btn.setIcon(icon2)
        self.continue_btn.setAutoRaise(True)
        self.continue_btn.setObjectName("continue_btn")
        self.horizontalLayout.addWidget(self.continue_btn)
        self.verticalLayout.addWidget(self.left_area_top_frame)
        self.scrollArea = QtGui.QScrollArea(self.left_area_frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 412, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.check_item_layout = QtGui.QVBoxLayout()
        self.check_item_layout.setSpacing(0)
        self.check_item_layout.setObjectName("check_item_layout")
        self.verticalLayout_6.addLayout(self.check_item_layout)
        spacerItem1 = QtGui.QSpacerItem(20, 371, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_4.addWidget(self.left_area_frame)
        self.right_area_frame = QtGui.QFrame(check_dialog)
        self.right_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.right_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.right_area_frame.setObjectName("right_area_frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.right_area_frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.right_area_top_frame = QtGui.QFrame(self.right_area_frame)
        self.right_area_top_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.right_area_top_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.right_area_top_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.right_area_top_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.right_area_top_frame.setObjectName("right_area_top_frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.right_area_top_frame)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.right_area_top_frame)
        self.label_3.setStyleSheet("font: 87 9pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.clear_info_btn = QtGui.QToolButton(self.right_area_top_frame)
        self.clear_info_btn.setIcon(icon)
        self.clear_info_btn.setAutoRaise(True)
        self.clear_info_btn.setObjectName("clear_info_btn")
        self.horizontalLayout_2.addWidget(self.clear_info_btn)
        self.verticalLayout_3.addWidget(self.right_area_top_frame)
        self.splitter = QtGui.QSplitter(self.right_area_frame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.output_screen = QtGui.QPlainTextEdit(self.splitter)
        self.output_screen.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.output_screen.setReadOnly(True)
        self.output_screen.setObjectName("output_screen")
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.counter_label = QtGui.QLabel(self.frame)
        self.counter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.counter_label.setObjectName("counter_label")
        self.verticalLayout_2.addWidget(self.counter_label)
        self.error_node_list = QtGui.QListWidget(self.frame)
        self.error_node_list.setObjectName("error_node_list")
        self.verticalLayout_2.addWidget(self.error_node_list)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_4.addWidget(self.right_area_frame)
        self.horizontalLayout_4.setStretch(1, 10)
        self.main_layout.addLayout(self.horizontalLayout_4)
        self.bottom_frame = QtGui.QFrame(check_dialog)
        self.bottom_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cancle_btn = QtGui.QPushButton(self.bottom_frame)
        self.cancle_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.cancle_btn.setObjectName("cancle_btn")
        self.horizontalLayout_3.addWidget(self.cancle_btn)
        self.next_btn = QtGui.QPushButton(self.bottom_frame)
        self.next_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_3.addWidget(self.next_btn)
        self.main_layout.addWidget(self.bottom_frame)
        self.main_layout.setStretch(0, 10)

        self.retranslateUi(check_dialog)
        QtCore.QObject.connect(self.clear_info_btn, QtCore.SIGNAL("clicked()"), self.output_screen.clear)
        QtCore.QMetaObject.connectSlotsByName(check_dialog)

    def retranslateUi(self, check_dialog):
        check_dialog.setWindowTitle(QtGui.QApplication.translate("check_dialog", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("check_dialog", "Cheker Item", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_check.setText(QtGui.QApplication.translate("check_dialog", "Repair ", None, QtGui.QApplication.UnicodeUTF8))
        self.check_seleted.setText(QtGui.QApplication.translate("check_dialog", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_btn.setText(QtGui.QApplication.translate("check_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.batch_run_btn.setText(QtGui.QApplication.translate("check_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.continue_btn.setText(QtGui.QApplication.translate("check_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("check_dialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_info_btn.setText(QtGui.QApplication.translate("check_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.counter_label.setText(QtGui.QApplication.translate("check_dialog", "Error List (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.cancle_btn.setText(QtGui.QApplication.translate("check_dialog", "Cancle", None, QtGui.QApplication.UnicodeUTF8))
        self.next_btn.setText(QtGui.QApplication.translate("check_dialog", "publish", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
